<div style='width: 25%; float: left;'>
    <div class="shadowbox suggestion cf" style='margin: 10px;' data-imdbid='{F_IMDB_ID}'>
        <table width="100%">
            <tr>
                <td>
                    <a class='lightbox' href='http://www.pickr.com/thumb.php?file={F_IMAGE}&size=600' title='{F_TITLE}'><img src="http://www.pickr.com/thumb.php?file={F_IMAGE}&sizex=80&sizey=60" alt='{F_TITLE} Poster' border="0" style='margin-right:10px;'/></a>
                </td>
                <td align='center'>
                    <h4>{F_TITLE}</h4>
                    {VOTE_INFO}
                </td>
            </tr>
        </table>
    </div>
</div>