<div style='width: 25%; float: left;'>
    <div class="shadowbox suggestion cf" style='margin: 10px;' data-imdbid='{F_IMDB_ID}'>
        <table width="100%">
            <tr>
                <td>
                    <img src="http://www.pickr.com/thumb.php?file={F_IMAGE}&sizex=100&sizey=80" alt='{F_TITLE} Poster' border="0" style='margin-right:10px;'/>
                </td>
                <td>
                    <h4>{F_TITLE}</h4>
                    <p class='center'>{VOTE_INFO}</p>
                </td>
            </tr>
        </table>
    </div>
</div>